development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: redis_cache
      hosts:
        - localhost:27017
      options:
  options:
    preload_models: true
    raise_not_found_error: false

test:
  sessions:
    default:
      database: redis_cache_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0